services:
  mysql:
    image: mysql:8.0.44-debian
    container_name: skadi_mysql
    restart: always
    env_file:
      - ./mysql/.env
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql:rw
    networks:
      main_network:

  redis:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: skadi_redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data:rw
    networks:
      main_network:
    command: redis-stack-server --save 60 1 --appendonly no --dir /data --dbfilename dump.rdb

  backend:
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    container_name: skadi_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      main_network:
    depends_on:
      - mysql
      - redis

networks:
  main_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
