server:
  port: 8080 # server port
  shutdown_timeout: 2s # timeout to force shutdown server after receiving an OS signal

logging:
  log_level: 1 # 1 - debug, 2 - info (default), 3 - warn, 4 - error, 5 - silent
  json_format: true # use JSON format if true

db:
  user: "scadi" # db user
  name: "scadi" # database name
  host: "127.0.0.1" # db host
  port: 3306 # db port
  migrations_url: file://migrations # path to dir with db migrations
