server:
  port: 8000 # server port
  shutdown_timeout: 1s # timeout to force shutdown server after receiving an OS signal
  cors:
    allowed_origins: "*" # comma-separated allowed origins for cors
    allowed_methods: "GET,HEAD,POST,OPTIONS" # comma-separated allowed methods for cors
    allow_credentials: false # set allow credentials for cors if true
  auth:
    token:
      access_ttl: 1m # access JWT-token expiration duration
      refresh_ttl: 3m # refresh JWT-token expiration duration
    cookie:
      path: "/api/v1/auth/private/" # cookie path
      secure: false # enable cookie secure if true
      http_only: false # enable cookie HTTP-only if true
      same_site: "" # cookie same site mode ("None", "Strict" or "Lax")

logging:
  log_level: 1 # 1 - debug, 2 - info (default), 3 - warn, 4 - error, 5 - silent
  json_format: true # use JSON format if true

cache:
  host: "127.0.0.1" # cache host
  port: 6379 # cache port

db:
  user: "test_user" # db user
  name: "skadi" # database name
  host: "127.0.0.1" # db host
  port: 3306 # db port
  migration:
    src: file://migrations # URL to dir with db migrations
